services:
  tripbundles-app-dev:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    container_name: tripbundles-app-dev
    ports:
      - "3001:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - tripbundles-dev-network

volumes:
  postgres_dev_data:

networks:
  tripbundles-dev-network:
    driver: bridge 